### ISSUE TITLE
Svelte is listed in the compatible languages 

### ISSUE THREAD

**Issue by JimNayzium** [Zxynine/EvenBetterComments#14] opened 2023-10-09 17:44 UTC
My .svelte files don't ever pull in the highlights.
If I copy and paste the javascript in the svelte file to a .js file it colors it immediately.
Is there anything special we need to do enable code highlighting inside <script> tags in the .svelte files?

Thanks for the great extension otherwise!

**Comment by Zxynine** [comment] 2024-06-25 20:34
Hey, sorry to say but if you are referring to a language inside of another, like how you can have JavaScript code in a html file, those are embedded languages and as per Issue #6 there is not support for that yet. Only comments in the native language of the document is supported. I am looking to rework this extension soon so who knows, I may find a solution to that problem.

**Comment by Zxynine** [comment] 2024-06-30 14:25
As I have been working on other fixes I have become more confident that embedded languages may be possible to support, I will start work on that soon. If I can manage this It will be the only extension that I know of that's able to handle embedded language comment highlighting for any language instead of being hard coded to support specific ones. In the meantime I will close this issue as a duplicate of #6.

**Closed as completed** 2024-06-30 14:26 UTC
Labels: duplicate, enhancement
